[BE] 북클럽 생성, 조회 기능 구현
bookkbookk/bookkbookk pull request #23
Opened 2023-10-18 10:19 UTC by swinb

### 구현한 기능이 어떤 건가요?
-북클럽 생성
-현재 로그인한 회원이 속한 북클럽 조회

### 구현 방식, 기술을 택한 이유가 있다면 설명해 주세요
- 현재 북클럽 조회를 토큰을 파싱하여 해당 멤버가 속한 북클럽만 응답하도록 했습니다
- 이유는 북클럽을 관리하기 위한 웹이라고 생각해서 가입은 초대 방식으로 하고, 소속된 북클럽만 보여주는게 좋지 않을까 생각했습니다.

### 리뷰어에게 한마디 부탁드려요.
- 에러 핸들링 미구현이라 나그 코드 머지되면 수정해야 할 것 같아요!

2023-10-18 13:04 UTC, nag0124 requested changes

2023-10-19 01:24 UTC, swinb commented on be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java
> +        mapper.disable(SerializationFeature.FAIL_ON_EMPTY_BEANS);
MultipartFile을 생성해서 넣어줄 때 에러가 떠서 stackoverflow에서 긁어온 내용인데 
저거 말고 다른 방법으로 해결했는데 까먹고 냅두고 있었네요 ObjectMapper랑 같이 삭제하겠습니다

2023-10-19 01:25 UTC, swinb commented on be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java
> +    private ObjectMapper mapper;
삭제하겠습니당

2023-10-19 01:28 UTC, swinb commented on be/src/main/java/codesquad/bookkbookk/bookclub/data/entity/MemberBookClub.java
> +    public static MemberBookClub of(Member member, BookClub bookClub) {
넵 생성자로 써도 될 것 같아요
다른 객체들은 정적 팩토리 메소드로 만드는 느낌들이 있었어서 일단 통일성을 위해 요렇게 해놨습니다

2023-10-19 01:30 UTC, swinb commented on be/src/main/java/codesquad/bookkbookk/bookclub/data/entity/BookClub.java
> +    public static BookClub from(Long creatorId, String name, String profileImgUrl){
request 를 받아서 만들어준다면 image upload를 이곳에서 해줘야 해서 이렇게 유지하는 게 좋다고 생각합니다

2023-10-19 01:40 UTC, swinb commented on be/src/main/java/codesquad/bookkbookk/bookclub/data/dto/CreateBookClubResponse.java
> +public class CreateBookClubResponse {
저는 행위가 가장 앞에 나오는 것도 좋다고 생각해요 
https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/java/example_code/s3/src/main/java/aws/example/s3
ec2 예제 오픈소스인데 다른 패키지들도 행위가 앞에 오더라구요

2023-10-19 02:38 UTC, nag0124 approved these changes

2023-10-19 02:38 UTC, merged